# Generated by Django 3.2.25 on 2024-12-03 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0002_auto_20241203_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='garages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property_images/'),
            preserve_default=False,
        ),
    ]
