# Generated by Django 3.2.25 on 2024-12-04 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0003_auto_20241203_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('new', 'New')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
